name: 'action-fourcalver'
description: 'Outputs a calver string in the format {year}.{month}.{day}.{seconds-in-day} (UTC).'
branding:
  icon: 'calendar'
  color: 'green'
outputs:
  result:
    description: 'The calver string in the format {year}.{month}.{day}.{seconds-in-day} (UTC)'
runs:
  using: 'node20'
  main: 'index.js'
