name: 'Caldendar versioning'
description: 'Returns a calver string as `{year}.{month}.{day}.{seconds-in-day}`.'
branding:
  icon: 'message-square'
  color: 'green'
outputs:
  result:
    description: 'A calver string as `{year}.{month}.{day}.{seconds-in-day}`.'
runs:
  using: 'node20'
  main: 'dist/index.js'
