name: 'action-fourcalver'
description: 'Outputs a calver string in the format {year}.{month}.{day}.{revision} (UTC), where revision is mapped from seconds-in-day to 0-65534.'
branding:
  icon: 'calendar'
  color: 'green'
outputs:
  result:
    description: 'The calver string in the format {year}.{month}.{day}.{revision} (UTC), where month and day are not zero-padded and revision is mapped percent-wise from seconds since midnight UTC (0-86399) to 0-65534.'
runs:
  using: 'node20'
  main: 'dist/index.js'
