name: Test Workflow
on:
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run workflow
        id: fourcalver
        uses: emptyother/action-fourcalver@v1
      - name: Show output
        run: |
          echo "Result: ${{ steps.fourcalver.outputs.result }}"
      - name: Validate calver format
        run: |
          if [[ ! "${{ steps.fourcalver.outputs.result }}" =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$ ]]; then
            echo "Calver format invalid: ${{ steps.fourcalver.outputs.result }}"
            exit 1
          fi
