name: Echo Text Action
on:
  workflow_dispatch:
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      - name: Run workflow
        id: fourcalver
        uses: emptyother/action-fourcalver@v1
      - name: Show output
        run: |
          echo "Result: ${{ steps.fourcalver.outputs.result }}"
